
// User Types
export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA'
export const REFRESHON = 'REFRESHON'
export const REFRESHOFF = 'REFRESHOFF'
export const REFRESHTOKEN = 'REFRESHTOKEN'
export const LOGOUT = 'LOGOUT'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'

// Settings
export const SHOW_LOADING = 'SHOW_LOADING'
export const SET_THEME = 'SET_THEME'
export const HIDE_LOADING = 'HIDE_LOADING'
export const SHOW_ALERT = 'SHOW_ALERT'
export const HIDE_ALERT = 'HIDE_ALERT'

// Contacts
export const SET_CONTACTS = 'SET_CONTACTS'
export const ADD_CONTACT = 'ADD_CONTACT'
export const DELETE_CONTACT = 'DELETE_CONTACT'
export const UPDATE_CONTACT = 'UPDATE_CONTACT'

// Contact Lists
export const SET_CONTACT_LISTS = 'SET_CONTACT_LISTS'
export const ADD_CONTACT_LIST = 'ADD_CONTACT_LIST'
export const DELETE_CONTACT_LIST = 'DELETE_CONTACT_LIST'
export const UPDATE_CONTACT_LIST = 'UPDATE_CONTACT_LIST'

// Email Campaigns
export const SET_EMAIL_CAMPAIGNS = 'SET_EMAIL_CAMPAIGNS'
export const ADD_EMAIL_CAMPAIGNS = 'ADD_EMAIL_CAMPAIGNS'
export const DELETE_EMAIL_CAMPAIGNS = 'DELETE_EMAIL_CAMPAIGNS'
export const UPDATE_EMAIL_CAMPAIGNS = 'UPDATE_EMAIL_CAMPAIGNS'
