version: '3'
services:
  cher_ami_server:
    build:
      context: ./server
    ports:
      - "8005:8005"
    container_name: cher_ami_server

  cher_ami_client:
    build:
      context: ./client
    ports:
      - "3005:3005"
    container_name: cher_ami_client
